<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
$cities = array(
 array('name' => 'Adilabad', 'state_id' => '1'),
 array('name' => 'Adoni', 'state_id' => '1'),
 array('name' => 'Amadalavalasa', 'state_id' => '1'),
 array('name' => 'Amalapuram', 'state_id' => '1'),
 array('name' => 'Anakapalle', 'state_id' => '1'),
 array('name' => 'Anantapur', 'state_id' => '1'),
 array('name' => 'Badepalle', 'state_id' => '1'),
 array('name' => 'Banganapalle', 'state_id' => '1'),
 array('name' => 'Bapatla', 'state_id' => '1'),
 array('name' => 'Bellampalle', 'state_id' => '1'),
 array('name' => 'Bethamcherla', 'state_id' => '1'),
 array('name' => 'Bhadrachalam', 'state_id' => '1'),
 array('name' => 'Bhainsa', 'state_id' => '1'),
 array('name' => 'Bheemunipatnam', 'state_id' => '1'),
 array('name' => 'Bhimavaram', 'state_id' => '1'),
 array('name' => 'Bhongir', 'state_id' => '1'),
 array('name' => 'Bobbili', 'state_id' => '1'),
 array('name' => 'Bodhan', 'state_id' => '1'),
 array('name' => 'Chilakaluripet', 'state_id' => '1'),
 array('name' => 'Chirala', 'state_id' => '1'),
 array('name' => 'Chittoor', 'state_id' => '1'),
 array('name' => 'Cuddapah', 'state_id' => '1'),
 array('name' => 'Devarakonda', 'state_id' => '1'),
 array('name' => 'Dharmavaram', 'state_id' => '1'),
 array('name' => 'Eluru', 'state_id' => '1'),
 array('name' => 'Farooqnagar', 'state_id' => '1'),
 array('name' => 'Gadwal', 'state_id' => '1'),
 array('name' => 'Gooty', 'state_id' => '1'),
 array('name' => 'Gudivada', 'state_id' => '1'),
 array('name' => 'Gudur', 'state_id' => '1'),
 array('name' => 'Guntakal', 'state_id' => '1'),
 array('name' => 'Guntur', 'state_id' => '1'),
 array('name' => 'Hanuman Junction', 'state_id' => '1'),
 array('name' => 'Hindupur', 'state_id' => '1'),
 array('name' => 'Hyderabad', 'state_id' => '1'),
 array('name' => 'Ichchapuram', 'state_id' => '1'),
 array('name' => 'Jaggaiahpet', 'state_id' => '1'),
 array('name' => 'Jagtial', 'state_id' => '1'),
 array('name' => 'Jammalamadugu', 'state_id' => '1'),
 array('name' => 'Jangaon', 'state_id' => '1'),
 array('name' => 'Kadapa', 'state_id' => '1'),
 array('name' => 'Kadiri', 'state_id' => '1'),
 array('name' => 'Kagaznagar', 'state_id' => '1'),
 array('name' => 'Kakinada', 'state_id' => '1'),
 array('name' => 'Kalyandurg', 'state_id' => '1'),
 array('name' => 'Kamareddy', 'state_id' => '1'),
 array('name' => 'Kandukur', 'state_id' => '1'),
 array('name' => 'Karimnagar', 'state_id' => '1'),
 array('name' => 'Kavali', 'state_id' => '1'),
 array('name' => 'Khammam', 'state_id' => '1'),
 array('name' => 'Koratla', 'state_id' => '1'),
 array('name' => 'Kothagudem', 'state_id' => '1'),
 array('name' => 'Kothapeta', 'state_id' => '1'),
 array('name' => 'Kovvur', 'state_id' => '1'),
 array('name' => 'Kurnool', 'state_id' => '1'),
 array('name' => 'Kyathampalle', 'state_id' => '1'),
 array('name' => 'Macherla', 'state_id' => '1'),
 array('name' => 'Machilipatnam', 'state_id' => '1'),
 array('name' => 'Madanapalle', 'state_id' => '1'),
 array('name' => 'Mahbubnagar', 'state_id' => '1'),
 array('name' => 'Mancherial', 'state_id' => '1'),
 array('name' => 'Mandamarri', 'state_id' => '1'),
 array('name' => 'Mandapeta', 'state_id' => '1'),
 array('name' => 'Manuguru', 'state_id' => '1'),
 array('name' => 'Markapur', 'state_id' => '1'),
 array('name' => 'Medak', 'state_id' => '1'),
 array('name' => 'Miryalaguda', 'state_id' => '1'),
 array('name' => 'Mogalthur', 'state_id' => '1'),
 array('name' => 'Nagari', 'state_id' => '1'),
 array('name' => 'Nagarkurnool', 'state_id' => '1'),
 array('name' => 'Nandyal', 'state_id' => '1'),
 array('name' => 'Narasapur', 'state_id' => '1'),
 array('name' => 'Narasaraopet', 'state_id' => '1'),
 array('name' => 'Narayanpet', 'state_id' => '1'),
 array('name' => 'Narsipatnam', 'state_id' => '1'),
 array('name' => 'Nellore', 'state_id' => '1'),
 array('name' => 'Nidadavole', 'state_id' => '1'),
 array('name' => 'Nirmal', 'state_id' => '1'),
 array('name' => 'Nizamabad', 'state_id' => '1'),
 array('name' => 'Nuzvid', 'state_id' => '1'),
 array('name' => 'Ongole', 'state_id' => '1'),
 array('name' => 'Palacole', 'state_id' => '1'),
 array('name' => 'Palasa Kasibugga', 'state_id' => '1'),
 array('name' => 'Palwancha', 'state_id' => '1'),
 array('name' => 'Parvathipuram', 'state_id' => '1'),
 array('name' => 'Pedana', 'state_id' => '1'),
 array('name' => 'Peddapuram', 'state_id' => '1'),
 array('name' => 'Pithapuram', 'state_id' => '1'),
 array('name' => 'Pondur', 'state_id' => '1'),
 array('name' => 'Ponnur', 'state_id' => '1'),
 array('name' => 'Proddatur', 'state_id' => '1'),
 array('name' => 'Punganur', 'state_id' => '1'),
 array('name' => 'Puttur', 'state_id' => '1'),
 array('name' => 'Rajahmundry', 'state_id' => '1'),
 array('name' => 'Rajam', 'state_id' => '1'),
 array('name' => 'Ramachandrapuram', 'state_id' => '1'),
 array('name' => 'Ramagundam', 'state_id' => '1'),
 array( 'name' => 'Rayachoti', 'state_id' => '1'),
 array( 'name' => 'Rayadurg', 'state_id' => '1'),
 array( 'name' => 'Renigunta', 'state_id' => '1'),
 array( 'name' => 'Repalle', 'state_id' => '1'),
 array( 'name' => 'Sadasivpet', 'state_id' => '1'),
 array( 'name' => 'Salur', 'state_id' => '1'),
 array( 'name' => 'Samalkot', 'state_id' => '1'),
 array( 'name' => 'Sangareddy', 'state_id' => '1'),
 array( 'name' => 'Sattenapalle', 'state_id' => '1'),
 array( 'name' => 'Siddipet', 'state_id' => '1'),
 array( 'name' => 'Singapur', 'state_id' => '1'),
 array( 'name' => 'Sircilla', 'state_id' => '1'),
 array( 'name' => 'Srikakulam', 'state_id' => '1'),
 array( 'name' => 'Srikalahasti', 'state_id' => '1'),
 array( 'name' => 'Suryapet', 'state_id' => '1'),
 array( 'name' => 'Tadepalligudem', 'state_id' => '1'),
 array( 'name' => 'Tadpatri', 'state_id' => '1'),
 array( 'name' => 'Tandur', 'state_id' => '1'),
 array( 'name' => 'Tanuku', 'state_id' => '1'),
 array( 'name' => 'Tenali', 'state_id' => '1'),
 array( 'name' => 'Tirupati', 'state_id' => '1'),
 array( 'name' => 'Tuni', 'state_id' => '1'),
 array( 'name' => 'Uravakonda', 'state_id' => '1'),
 array( 'name' => 'Venkatagiri', 'state_id' => '1'),
 array( 'name' => 'Vicarabad', 'state_id' => '1'),
 array( 'name' => 'Vijayawada', 'state_id' => '1'),
 array( 'name' => 'Vinukonda', 'state_id' => '1'),
 array( 'name' => 'Visakhapatnam', 'state_id' => '1'),
 array( 'name' => 'Vizianagaram', 'state_id' => '1'),
 array( 'name' => 'Wanaparthy', 'state_id' => '1'),
 array( 'name' => 'Warangal', 'state_id' => '1'),
 array( 'name' => 'Yellandu', 'state_id' => '1'),
 array( 'name' => 'Yemmiganur', 'state_id' => '1'),
 array( 'name' => 'Yerraguntla', 'state_id' => '1'),
 array( 'name' => 'Zahirabad', 'state_id' => '1'),
 array( 'name' => 'Rajampet', 'state_id' => '1'),
 array( 'name' => 'Along', 'state_id' => '2'),
 array( 'name' => 'Bomdila', 'state_id' => '2'),
 array( 'name' => 'Itanagar', 'state_id' => '2'),
 array( 'name' => 'Naharlagun', 'state_id' => '2'),
 array( 'name' => 'Pasighat', 'state_id' => '2'),
 array( 'name' => 'Abhayapuri', 'state_id' => '3'),
 array( 'name' => 'Amguri', 'state_id' => '3'),
 array( 'name' => 'Anandnagaar', 'state_id' => '3'),
 array( 'name' => 'Barpeta', 'state_id' => '3'),
 array( 'name' => 'Barpeta Road', 'state_id' => '3'),
 array( 'name' => 'Bilasipara', 'state_id' => '3'),
 array( 'name' => 'Bongaigaon', 'state_id' => '3'),
 array( 'name' => 'Dhekiajuli', 'state_id' => '3'),
 array( 'name' => 'Dhubri', 'state_id' => '3'),
 array( 'name' => 'Dibrugarh', 'state_id' => '3'),
 array( 'name' => 'Digboi', 'state_id' => '3'),
 array( 'name' => 'Diphu', 'state_id' => '3'),
 array( 'name' => 'Dispur', 'state_id' => '3'),
 array( 'name' => 'Gauripur', 'state_id' => '3'),
 array( 'name' => '6lpara', 'state_id' => '3'),
 array( 'name' => 'Golaghat', 'state_id' => '3'),
 array( 'name' => 'Guwahati', 'state_id' => '3'),
 array( 'name' => 'Haflong', 'state_id' => '3'),
 array( 'name' => 'Hailakandi', 'state_id' => '3'),
 array( 'name' => 'Hojai', 'state_id' => '3'),
 array( 'name' => 'Jorhat', 'state_id' => '3'),
 array( 'name' => 'Karimganj', 'state_id' => '3'),
 array( 'name' => 'Kokrajhar', 'state_id' => '3'),
 array( 'name' => 'Lanka', 'state_id' => '3'),
 array( 'name' => 'Lumding', 'state_id' => '3'),
 array( 'name' => 'Mangaldoi', 'state_id' => '3'),
 array( 'name' => 'Mankachar', 'state_id' => '3'),
 array( 'name' => 'Margherita', 'state_id' => '3'),
 array( 'name' => 'Mariani', 'state_id' => '3'),
 array( 'name' => 'Marigaon', 'state_id' => '3'),
 array( 'name' => 'Nagaon', 'state_id' => '3'),
 array( 'name' => 'Nalbari', 'state_id' => '3'),
 array( 'name' => 'North Lakhimpur', 'state_id' => '3'),
 array( 'name' => 'Rangia', 'state_id' => '3'),
 array( 'name' => 'Sibsagar', 'state_id' => '3'),
 array( 'name' => 'Silapathar', 'state_id' => '3'),
 array( 'name' => 'Silchar', 'state_id' => '3'),
 array( 'name' => 'Tezpur', 'state_id' => '3'),
 array( 'name' => 'Tinsukia', 'state_id' => '3'),
 array( 'name' => 'Amarpur', 'state_id' => '4'),
 array( 'name' => 'Araria', 'state_id' => '4'),
 array( 'name' => 'Areraj', 'state_id' => '4'),
 array( 'name' => 'Arrah', 'state_id' => '4'),
 array( 'name' => 'Asarganj', 'state_id' => '4'),
 array( 'name' => 'Aurangabad', 'state_id' => '4'),
 array( 'name' => 'Bagaha', 'state_id' => '4'),
 array( 'name' => 'Bahadurganj', 'state_id' => '4'),
 array( 'name' => 'Bairgania', 'state_id' => '4'),
 array( 'name' => 'Bakhtiarpur', 'state_id' => '4'),
 array( 'name' => 'Banka', 'state_id' => '4'),
 array( 'name' => 'Banmankhi Bazar', 'state_id' => '4'),
 array( 'name' => 'Barahiya', 'state_id' => '4'),
 array( 'name' => 'Barauli', 'state_id' => '4'),
 array( 'name' => 'Barbigha', 'state_id' => '4'),
 array( 'name' => 'Barh', 'state_id' => '4'),
 array( 'name' => 'Begusarai', 'state_id' => '4'),
 array( 'name' => 'Behea', 'state_id' => '4'),
 array( 'name' => 'Bettiah', 'state_id' => '4'),
 array( 'name' => 'Bhabua', 'state_id' => '4'),
 array( 'name' => 'Bhagalpur', 'state_id' => '4'),
 array( 'name' => '4 Sharif', 'state_id' => '4'),
 array( 'name' => 'Bikramganj', 'state_id' => '4'),
 array( 'name' => 'Bodh Gaya', 'state_id' => '4'),
 array( 'name' => 'Buxar', 'state_id' => '4'),
 array( 'name' => 'Chandan Bara', 'state_id' => '4'),
 array( 'name' => 'Chanpatia', 'state_id' => '4'),
 array( 'name' => 'Chhapra', 'state_id' => '4'),
 array( 'name' => 'Colgong', 'state_id' => '4'),
 array( 'name' => 'Dalsinghsarai', 'state_id' => '4'),
 array( 'name' => 'Darbhanga', 'state_id' => '4'),
 array( 'name' => 'Daudnagar', 'state_id' => '4'),
 array( 'name' => 'Dehri-on-Sone', 'state_id' => '4'),
 array( 'name' => 'Dhaka', 'state_id' => '4'),
 array( 'name' => 'Dighwara', 'state_id' => '4'),
 array( 'name' => 'Dumraon', 'state_id' => '4'),
 array( 'name' => 'Fatwah', 'state_id' => '4'),
 array( 'name' => 'Forbesganj', 'state_id' => '4'),
 array( 'name' => 'Gaya', 'state_id' => '4'),
 array( 'name' => 'Gogri Jamalpur', 'state_id' => '4'),
 array( 'name' => 'Gopalganj', 'state_id' => '4'),
 array( 'name' => 'Hajipur', 'state_id' => '4'),
 array( 'name' => 'Hilsa', 'state_id' => '4'),
 array( 'name' => 'Hisua', 'state_id' => '4'),
 array( 'name' => 'Islampur', 'state_id' => '4'),
 array( 'name' => 'Jagdispur', 'state_id' => '4'),
 array( 'name' => 'Jamalpur', 'state_id' => '4'),
 array( 'name' => 'Jamui', 'state_id' => '4'),
 array( 'name' => 'Jehanabad', 'state_id' => '4'),
 array( 'name' => 'Jhajha', 'state_id' => '4'),
 array( 'name' => 'Jhanjharpur', 'state_id' => '4'),
 array( 'name' => 'Jogabani', 'state_id' => '4'),
 array( 'name' => 'Kanti', 'state_id' => '4'),
 array( 'name' => 'Katihar', 'state_id' => '4'),
 array( 'name' => 'Khagaria', 'state_id' => '4'),
 array( 'name' => 'Kharagpur', 'state_id' => '4'),
 array( 'name' => 'Kishanganj', 'state_id' => '4'),
 array( 'name' => 'Lakhisarai', 'state_id' => '4'),
 array( 'name' => 'Lalganj', 'state_id' => '4'),
 array( 'name' => 'Madhepura', 'state_id' => '4'),
 array( 'name' => 'Madhubani', 'state_id' => '4'),
 array( 'name' => 'Maharajganj', 'state_id' => '4'),
 array( 'name' => 'Mahnar Bazar', 'state_id' => '4'),
 array( 'name' => 'Makhdumpur', 'state_id' => '4'),
 array( 'name' => 'Maner', 'state_id' => '4'),
 array( 'name' => 'Manihari', 'state_id' => '4'),
 array( 'name' => 'Marhaura', 'state_id' => '4'),
 array( 'name' => 'Masaurhi', 'state_id' => '4'),
 array( 'name' => 'Mirganj', 'state_id' => '4'),
 array( 'name' => 'Mokameh', 'state_id' => '4'),
 array( 'name' => 'Motihari', 'state_id' => '4'),
 array( 'name' => 'Motipur', 'state_id' => '4'),
 array( 'name' => 'Munger', 'state_id' => '4'),
 array( 'name' => 'Murliganj', 'state_id' => '4'),
 array( 'name' => 'Muzaffarpur', 'state_id' => '4'),
 array( 'name' => 'Narkatiaganj', 'state_id' => '4'),
 array( 'name' => 'Naugachhia', 'state_id' => '4'),
 array( 'name' => 'Nawada', 'state_id' => '4'),
 array( 'name' => 'Nokha', 'state_id' => '4'),
 array( 'name' => 'Patna', 'state_id' => '4'),
 array( 'name' => 'Piro', 'state_id' => '4'),
 array( 'name' => 'Purnia', 'state_id' => '4'),
 array( 'name' => 'Rafiganj', 'state_id' => '4'),
 array( 'name' => 'Rajgir', 'state_id' => '4'),
 array( 'name' => 'Ramnagar', 'state_id' => '4'),
 array( 'name' => 'Raxaul Bazar', 'state_id' => '4'),
 array( 'name' => 'Revelganj', 'state_id' => '4'),
 array( 'name' => 'Rosera', 'state_id' => '4'),
 array( 'name' => 'Saharsa', 'state_id' => '4'),
 array( 'name' => 'Samastipur', 'state_id' => '4'),
 array( 'name' => 'Sasaram', 'state_id' => '4'),
 array( 'name' => 'Sheikhpura', 'state_id' => '4'),
 array( 'name' => 'Sheohar', 'state_id' => '4'),
 array( 'name' => 'Sherghati', 'state_id' => '4'),
 array( 'name' => 'Silao', 'state_id' => '4'),
 array( 'name' => 'Sitamarhi', 'state_id' => '4'),
 array( 'name' => 'Siwan', 'state_id' => '4'),
 array( 'name' => 'Sonepur', 'state_id' => '4'),
 array( 'name' => 'Sugauli', 'state_id' => '4'),
 array( 'name' => 'Sultanganj', 'state_id' => '4'),
 array( 'name' => 'Supaul', 'state_id' => '4'),
 array( 'name' => 'Warisaliganj', 'state_id' => '4'),
 array( 'name' => 'Ahiwara', 'state_id' => '5'),
 array( 'name' => 'Akaltara', 'state_id' => '5'),
 array( 'name' => 'Ambagarh Chowki', 'state_id' => '5'),
 array( 'name' => 'Ambikapur', 'state_id' => '5'),
 array( 'name' => 'Arang', 'state_id' => '5'),
 array( 'name' => 'Bade Bacheli', 'state_id' => '5'),
 array( 'name' => 'Balod', 'state_id' => '5'),
 array( 'name' => 'Baloda Bazar', 'state_id' => '5'),
 array( 'name' => 'Bemetra', 'state_id' => '5'),
 array( 'name' => 'Bhatapara', 'state_id' => '5'),
 array( 'name' => 'Bilaspur', 'state_id' => '5'),
 array( 'name' => 'Birgaon', 'state_id' => '5'),
 array( 'name' => 'Champa', 'state_id' => '5'),
 array( 'name' => 'Chirmiri', 'state_id' => '5'),
 array( 'name' => 'Dalli-Rajhara', 'state_id' => '5'),
 array( 'name' => 'Dhamtari', 'state_id' => '5'),
 array( 'name' => 'Dipka', 'state_id' => '5'),
 array( 'name' => 'Dongargarh', 'state_id' => '5'),
 array( 'name' => 'Durg-Bhilai Nagar', 'state_id' => '5'),
 array( 'name' => 'Gobranawapara', 'state_id' => '5'),
 array( 'name' => 'Jagdalpur', 'state_id' => '5'),
 array( 'name' => 'Janjgir', 'state_id' => '5'),
 array( 'name' => 'Jashpurnagar', 'state_id' => '5'),
 array( 'name' => 'Kanker', 'state_id' => '5'),
 array( 'name' => 'Kawardha', 'state_id' => '5'),
 array( 'name' => 'Kondagaon', 'state_id' => '5'),
 array( 'name' => 'Korba', 'state_id' => '5'),
 array( 'name' => 'Mahasamund', 'state_id' => '5'),
 array( 'name' => 'Mahendragarh', 'state_id' => '5'),
 array( 'name' => 'Mungeli', 'state_id' => '5'),
 array( 'name' => 'Naila Janjgir', 'state_id' => '5'),
 array( 'name' => 'Raigarh', 'state_id' => '5'),
 array( 'name' => 'Raipur', 'state_id' => '5'),
 array( 'name' => 'Rajnandgaon', 'state_id' => '5'),
 array( 'name' => 'Sakti', 'state_id' => '5'),
 array( 'name' => 'Tilda Newra', 'state_id' => '5'),
 array( 'name' => 'Aldona', 'state_id' => '6'),
 array( 'name' => 'Curchorem Cacora', 'state_id' => '6'),
 array( 'name' => 'Madgaon', 'state_id' => '6'),
 array( 'name' => 'Mapusa', 'state_id' => '6'),
 array( 'name' => 'Margao', 'state_id' => '6'),
 array( 'name' => 'Marmagao', 'state_id' => '6'),
 array( 'name' => 'Panaji', 'state_id' => '6'),
 array( 'name' => 'Ahmedabad', 'state_id' => '7'),
 array( 'name' => 'Amreli', 'state_id' => '7'),
 array( 'name' => 'Anand', 'state_id' => '7'),
 array( 'name' => 'Ankleshwar', 'state_id' => '7'),
 array( 'name' => 'Bharuch', 'state_id' => '7'),
 array( 'name' => 'Bhavnagar', 'state_id' => '7'),
 array( 'name' => 'Bhuj', 'state_id' => '7'),
 array( 'name' => 'Cambay', 'state_id' => '7'),
 array( 'name' => 'Dahod', 'state_id' => '7'),
 array( 'name' => 'Deesa', 'state_id' => '7'),
 array( 'name' => 'Dharampur', 'state_id' => '7'),
 array( 'name' => 'Dholka', 'state_id' => '7'),
 array( 'name' => 'Gandhinagar', 'state_id' => '7'),
 array( 'name' => 'Godhra', 'state_id' => '7'),
 array( 'name' => 'Himatnagar', 'state_id' => '7'),
 array( 'name' => 'Idar', 'state_id' => '7'),
 array( 'name' => 'Jamnagar', 'state_id' => '7'),
 array( 'name' => 'Junagadh', 'state_id' => '7'),
 array( 'name' => 'Kadi', 'state_id' => '7'),
 array( 'name' => 'Kalavad', 'state_id' => '7'),
 array( 'name' => 'Kalol', 'state_id' => '7'),
 array( 'name' => 'Kapadvanj', 'state_id' => '7'),
 array( 'name' => 'Karjan', 'state_id' => '7'),
 array( 'name' => 'Keshod', 'state_id' => '7'),
 array( 'name' => 'Khambhalia', 'state_id' => '7'),
 array( 'name' => 'Khambhat', 'state_id' => '7'),
 array( 'name' => 'Kheda', 'state_id' => '7'),
 array( 'name' => 'Khedbrahma', 'state_id' => '7'),
 array( 'name' => 'Kheralu', 'state_id' => '7'),
 array( 'name' => 'Kodinar', 'state_id' => '7'),
 array( 'name' => 'Lathi', 'state_id' => '7'),
 array( 'name' => 'Limbdi', 'state_id' => '7'),
 array( 'name' => 'Lunawada', 'state_id' => '7'),
 array( 'name' => 'Mahesana', 'state_id' => '7'),
 array( 'name' => 'Mahuva', 'state_id' => '7'),
 array( 'name' => 'Manavadar', 'state_id' => '7'),
 array( 'name' => 'Mandvi', 'state_id' => '7'),
 array( 'name' => 'Mangrol', 'state_id' => '7'),
 array( 'name' => 'Mansa', 'state_id' => '7'),
 array( 'name' => 'Mehmedabad', 'state_id' => '7'),
 array( 'name' => 'Modasa', 'state_id' => '7'),
 array( 'name' => 'Morvi', 'state_id' => '7'),
 array( 'name' => 'Nadiad', 'state_id' => '7'),
 array( 'name' => 'Navsari', 'state_id' => '7'),
 array( 'name' => 'Padra', 'state_id' => '7'),
 array( 'name' => 'Palanpur', 'state_id' => '7'),
 array( 'name' => 'Palitana', 'state_id' => '7'),
 array( 'name' => 'Pardi', 'state_id' => '7'),
 array( 'name' => 'Patan', 'state_id' => '7'),
 array( 'name' => 'Petlad', 'state_id' => '7'),
 array( 'name' => 'Porbandar', 'state_id' => '7'),
 array( 'name' => 'Radhanpur', 'state_id' => '7'),
 array( 'name' => 'Rajkot', 'state_id' => '7'),
 array( 'name' => 'Rajpipla', 'state_id' => '7'),
 array( 'name' => 'Rajula', 'state_id' => '7'),
 array( 'name' => 'Ranavav', 'state_id' => '7'),
 array( 'name' => 'Rapar', 'state_id' => '7'),
 array( 'name' => 'Salaya', 'state_id' => '7'),
 array( 'name' => 'Sanand', 'state_id' => '7'),
 array( 'name' => 'Savarkundla', 'state_id' => '7'),
 array( 'name' => 'Sidhpur', 'state_id' => '7'),
 array( 'name' => 'Sihor', 'state_id' => '7'),
 array( 'name' => 'Songadh', 'state_id' => '7'),
 array( 'name' => 'Surat', 'state_id' => '7'),
 array( 'name' => 'Talaja', 'state_id' => '7'),
 array( 'name' => 'Thangadh', 'state_id' => '7'),
 array( 'name' => 'Tharad', 'state_id' => '7'),
 array( 'name' => 'Umbergaon', 'state_id' => '7'),
 array( 'name' => 'Umreth', 'state_id' => '7'),
 array( 'name' => 'Una', 'state_id' => '7'),
 array( 'name' => 'Unjha', 'state_id' => '7'),
 array( 'name' => 'Upleta', 'state_id' => '7'),
 array( 'name' => 'Vadnagar', 'state_id' => '7'),
 array( 'name' => 'Vadodara', 'state_id' => '7'),
 array( 'name' => 'Valsad', 'state_id' => '7'),
 array( 'name' => 'Vapi', 'state_id' => '7'),
 array( 'name' => 'Vapi', 'state_id' => '7'),
 array( 'name' => 'Veraval', 'state_id' => '7'),
 array( 'name' => 'Vijapur', 'state_id' => '7'),
 array( 'name' => 'Viramgam', 'state_id' => '7'),
 array( 'name' => 'Visnagar', 'state_id' => '7'),
 array( 'name' => 'Vyara', 'state_id' => '7'),
 array( 'name' => 'Wadhwan', 'state_id' => '7'),
 array( 'name' => 'Wankaner', 'state_id' => '7'),
 array( 'name' => 'Adalaj', 'state_id' => '7'),
 array( 'name' => 'Adityana', 'state_id' => '7'),
 array( 'name' => 'Alang', 'state_id' => '7'),
 array( 'name' => 'Ambaji', 'state_id' => '7'),
 array( 'name' => 'Ambaliyasan', 'state_id' => '7'),
 array( 'name' => 'Andada', 'state_id' => '7'),
 array( 'name' => 'Anjar', 'state_id' => '7'),
 array( 'name' => 'Anklav', 'state_id' => '7'),
 array( 'name' => 'Antaliya', 'state_id' => '7'),
 array( 'name' => 'Arambhada', 'state_id' => '7'),
 array( 'name' => 'Atul', 'state_id' => '7'),
 array( 'name' => 'Ballabhgarh', 'state_id' => '8'),
 array( 'name' => 'Ambala', 'state_id' => '8'),
 array( 'name' => 'Ambala', 'state_id' => '8'),
 array( 'name' => 'Asankhurd', 'state_id' => '8'),
 array( 'name' => 'Assandh', 'state_id' => '8'),
 array( 'name' => 'Ateli', 'state_id' => '8'),
 array( 'name' => 'Babiyal', 'state_id' => '8'),
 array( 'name' => 'Bahadurgarh', 'state_id' => '8'),
 array( 'name' => 'Barwala', 'state_id' => '8'),
 array( 'name' => 'Bhiwani', 'state_id' => '8'),
 array( 'name' => 'Charkhi Dadri', 'state_id' => '8'),
 array( 'name' => 'Cheeka', 'state_id' => '8'),
 array( 'name' => 'Ellenabad 2', 'state_id' => '8'),
 array( 'name' => 'Faridabad', 'state_id' => '8'),
 array( 'name' => 'Fatehabad', 'state_id' => '8'),
 array( 'name' => 'Ganaur', 'state_id' => '8'),
 array( 'name' => 'Gharaunda', 'state_id' => '8'),
 array( 'name' => 'Gohana', 'state_id' => '8'),
 array( 'name' => 'Gurgaon', 'state_id' => '8'),
 array( 'name' => 'Haibat(Yamuna Nagar)', 'state_id' => '8'),
 array( 'name' => 'Hansi', 'state_id' => '8'),
 array( 'name' => 'Hisar', 'state_id' => '8'),
 array( 'name' => 'Hodal', 'state_id' => '8'),
 array( 'name' => 'Jhajjar', 'state_id' => '8'),
 array( 'name' => 'Jind', 'state_id' => '8'),
 array( 'name' => 'Kaithal', 'state_id' => '8'),
 array( 'name' => 'Kalan Wali', 'state_id' => '8'),
 array( 'name' => 'Kalka', 'state_id' => '8'),
 array( 'name' => 'Karnal', 'state_id' => '8'),
 array( 'name' => 'Ladwa', 'state_id' => '8'),
 array( 'name' => 'Mahendragarh', 'state_id' => '8'),
 array( 'name' => 'Mandi Dabwali', 'state_id' => '8'),
 array( 'name' => 'Narnaul', 'state_id' => '8'),
 array( 'name' => 'Narwana', 'state_id' => '8'),
 array( 'name' => 'Palwal', 'state_id' => '8'),
 array( 'name' => 'Panchkula', 'state_id' => '8'),
 array( 'name' => 'Panipat', 'state_id' => '8'),
 array( 'name' => 'Pehowa', 'state_id' => '8'),
 array( 'name' => 'Pinjore', 'state_id' => '8'),
 array( 'name' => 'Rania', 'state_id' => '8'),
 array( 'name' => 'Ratia', 'state_id' => '8'),
 array( 'name' => 'Rewari', 'state_id' => '8'),
 array( 'name' => 'Rohtak', 'state_id' => '8'),
 array( 'name' => 'Safidon', 'state_id' => '8'),
 array( 'name' => 'Samalkha', 'state_id' => '8'),
 array( 'name' => 'Shahbad', 'state_id' => '8'),
 array( 'name' => 'Sirsa', 'state_id' => '8'),
 array( 'name' => 'Sohna', 'state_id' => '8'),
 array( 'name' => 'Sonipat', 'state_id' => '8'),
 array( 'name' => 'Taraori', 'state_id' => '8'),
 array( 'name' => 'Thanesar', 'state_id' => '8'),
 array( 'name' => 'Tohana', 'state_id' => '8'),
 array( 'name' => 'Yamunanagar', 'state_id' => '8'),
 array( 'name' => 'Arki', 'state_id' => '9'),
 array( 'name' => 'Baddi', 'state_id' => '9'),
 array( 'name' => 'Bilaspur', 'state_id' => '9'),
 array( 'name' => 'Chamba', 'state_id' => '9'),
 array( 'name' => 'Dalhousie', 'state_id' => '9'),
 array( 'name' => 'Dharamsala', 'state_id' => '9'),
 array( 'name' => 'Hamirpur', 'state_id' => '9'),
 array( 'name' => 'Mandi', 'state_id' => '9'),
 array( 'name' => 'Nahan', 'state_id' => '9'),
 array( 'name' => 'Shimla', 'state_id' => '9'),
 array( 'name' => 'Solan', 'state_id' => '9'),
 array( 'name' => 'Sundarnagar', 'state_id' => '9'),
 array( 'name' => 'Amlabad', 'state_id' => '10'),
 array( 'name' => 'Ara', 'state_id' => '10'),
 array( 'name' => 'Barughutu', 'state_id' => '10'),
 array( 'name' => 'Bokaro Steel City', 'state_id' => '10'),
 array( 'name' => 'Chaibasa', 'state_id' => '10'),
 array( 'name' => 'Chakradharpur', 'state_id' => '10'),
 array( 'name' => 'Chandrapura', 'state_id' => '10'),
 array( 'name' => 'Chatra', 'state_id' => '10'),
 array( 'name' => 'Chirkunda', 'state_id' => '10'),
 array( 'name' => 'Churi', 'state_id' => '10'),
 array( 'name' => 'Daltonganj', 'state_id' => '10'),
 array( 'name' => 'Deoghar', 'state_id' => '10'),
 array( 'name' => 'Dhanbad', 'state_id' => '10'),
 array( 'name' => 'Dumka', 'state_id' => '10'),
 array( 'name' => 'Garhwa', 'state_id' => '10'),
 array( 'name' => 'Ghatshila', 'state_id' => '10'),
 array( 'name' => 'Giridih', 'state_id' => '10'),
 array( 'name' => 'Godda', 'state_id' => '10'),
 array( 'name' => 'Gomoh', 'state_id' => '10'),
 array( 'name' => 'Gumia', 'state_id' => '10'),
 array( 'name' => 'Gumla', 'state_id' => '10'),
 array( 'name' => 'Hazaribag', 'state_id' => '10'),
 array( 'name' => 'Hussainabad', 'state_id' => '10'),
 array( 'name' => 'Jamshedpur', 'state_id' => '10'),
 array( 'name' => 'Jamtara', 'state_id' => '10'),
 array( 'name' => 'Jhumri Tilaiya', 'state_id' => '10'),
 array( 'name' => 'Khunti', 'state_id' => '10'),
 array( 'name' => 'Lohardaga', 'state_id' => '10'),
 array( 'name' => 'Madhupur', 'state_id' => '10'),
 array( 'name' => 'Mihijam', 'state_id' => '10'),
 array( 'name' => 'Musabani', 'state_id' => '10'),
 array( 'name' => 'Pakaur', 'state_id' => '10'),
 array( 'name' => 'Patratu', 'state_id' => '10'),
 array( 'name' => 'Phusro', 'state_id' => '10'),
 array( 'name' => 'Ramngarh', 'state_id' => '10'),
 array( 'name' => 'Ranchi', 'state_id' => '10'),
 array( 'name' => 'Sahibganj', 'state_id' => '10'),
 array( 'name' => 'Saunda', 'state_id' => '10'),
 array( 'name' => 'Simdega', 'state_id' => '10'),
 array( 'name' => 'Tenu Dam-cum- Kathhara', 'state_id' => '10'),
 array( 'name' => 'Arasikere', 'state_id' => '11'),
 array( 'name' => 'Bangalore', 'state_id' => '11'),
 array( 'name' => 'Belgaum', 'state_id' => '11'),
 array( 'name' => 'Bellary', 'state_id' => '11'),
 array( 'name' => 'Chamrajnagar', 'state_id' => '11'),
 array( 'name' => 'Chikkaballapur', 'state_id' => '11'),
 array( 'name' => 'Chintamani', 'state_id' => '11'),
 array( 'name' => 'Chitradurga', 'state_id' => '11'),
 array( 'name' => 'Gulbarga', 'state_id' => '11'),
 array( 'name' => 'Gundlupet', 'state_id' => '11'),
 array( 'name' => 'Hassan', 'state_id' => '11'),
 array( 'name' => 'Hospet', 'state_id' => '11'),
 array( 'name' => 'Hubli', 'state_id' => '11'),
 array( 'name' => 'Karkala', 'state_id' => '11'),
 array( 'name' => 'Karwar', 'state_id' => '11'),
 array( 'name' => 'Kolar', 'state_id' => '11'),
 array( 'name' => 'Kota', 'state_id' => '11'),
 array( 'name' => 'Lakshmeshwar', 'state_id' => '11'),
 array( 'name' => 'Lingsugur', 'state_id' => '11'),
 array( 'name' => 'Maddur', 'state_id' => '11'),
 array( 'name' => 'Madhugiri', 'state_id' => '11'),
 array( 'name' => 'Madikeri', 'state_id' => '11'),
 array( 'name' => 'Magadi', 'state_id' => '11'),
 array( 'name' => 'Mahalingpur', 'state_id' => '11'),
 array( 'name' => 'Malavalli', 'state_id' => '11'),
 array( 'name' => 'Malur', 'state_id' => '11'),
 array( 'name' => 'Mandya', 'state_id' => '11'),
 array( 'name' => 'Mangalore', 'state_id' => '11'),
 array( 'name' => 'Manvi', 'state_id' => '11'),
 array( 'name' => 'Mudalgi', 'state_id' => '11'),
 array( 'name' => 'Mudbidri', 'state_id' => '11'),
 array( 'name' => 'Muddebihal', 'state_id' => '11'),
 array( 'name' => 'Mudhol', 'state_id' => '11'),
 array( 'name' => 'Mulbagal', 'state_id' => '11'),
 array( 'name' => 'Mundargi', 'state_id' => '11'),
 array( 'name' => 'Mysore', 'state_id' => '11'),
 array( 'name' => 'Nanjangud', 'state_id' => '11'),
 array( 'name' => 'Pavagada', 'state_id' => '11'),
 array( 'name' => 'Puttur', 'state_id' => '11'),
 array( 'name' => 'Rabkavi Banhatti', 'state_id' => '11'),
 array( 'name' => 'Raichur', 'state_id' => '11'),
 array( 'name' => 'Ramanagaram', 'state_id' => '11'),
 array( 'name' => 'Ramdurg', 'state_id' => '11'),
 array( 'name' => 'Ranibennur', 'state_id' => '11'),
 array( 'name' => 'Robertson Pet', 'state_id' => '11'),
 array( 'name' => 'Ron', 'state_id' => '11'),
 array( 'name' => 'Sadalgi', 'state_id' => '11'),
 array( 'name' => 'Sagar', 'state_id' => '11'),
 array( 'name' => 'Sakleshpur', 'state_id' => '11'),
 array( 'name' => 'Sandur', 'state_id' => '11'),
 array( 'name' => 'Sankeshwar', 'state_id' => '11'),
 array( 'name' => 'Saundatti-Yellamma', 'state_id' => '11'),
 array( 'name' => 'Savanur', 'state_id' => '11'),
 array( 'name' => 'Sedam', 'state_id' => '11'),
 array( 'name' => 'Shahabad', 'state_id' => '11'),
 array( 'name' => 'Shahpur', 'state_id' => '11'),
 array( 'name' => 'Shiggaon', 'state_id' => '11'),
 array( 'name' => 'Shikapur', 'state_id' => '11'),
 array( 'name' => 'Shimoga', 'state_id' => '11'),
 array( 'name' => 'Shorapur', 'state_id' => '11'),
 array( 'name' => 'Shrirangapattana', 'state_id' => '11'),
 array( 'name' => 'Sidlaghatta', 'state_id' => '11'),
 array( 'name' => 'Sindgi', 'state_id' => '11'),
 array( 'name' => 'Sindhnur', 'state_id' => '11'),
 array( 'name' => 'Sira', 'state_id' => '11'),
 array( 'name' => 'Sirsi', 'state_id' => '11'),
 array( 'name' => 'Siruguppa', 'state_id' => '11'),
 array( 'name' => 'Srinivaspur', 'state_id' => '11'),
 array( 'name' => 'Talikota', 'state_id' => '11'),
 array( 'name' => 'Tarikere', 'state_id' => '11'),
 array( 'name' => 'Tekkalakota', 'state_id' => '11'),
 array( 'name' => 'Terdal', 'state_id' => '11'),
 array( 'name' => 'Tiptur', 'state_id' => '11'),
 array( 'name' => 'Tumkur', 'state_id' => '11'),
 array( 'name' => 'Udupi', 'state_id' => '11'),
 array( 'name' => 'Vijayapura', 'state_id' => '11'),
 array( 'name' => 'Wadi', 'state_id' => '11'),
 array( 'name' => 'Yadgir', 'state_id' => '11'),
 array( 'name' => 'Adoor', 'state_id' => '12'),
 array( 'name' => 'Akathiyoor', 'state_id' => '12'),
 array( 'name' => 'Alappuzha', 'state_id' => '12'),
 array( 'name' => 'Ancharakandy', 'state_id' => '12'),
 array( 'name' => 'Aroor', 'state_id' => '12'),
 array( 'name' => 'Ashtamichira', 'state_id' => '12'),
 array( 'name' => 'Attingal', 'state_id' => '12'),
 array( 'name' => 'Avinissery', 'state_id' => '12'),
 array( 'name' => 'Chalakudy', 'state_id' => '12'),
 array( 'name' => 'Changanassery', 'state_id' => '12'),
 array( 'name' => 'Chendamangalam', 'state_id' => '12'),
 array( 'name' => 'Chengannur', 'state_id' => '12'),
 array( 'name' => 'Cherthala', 'state_id' => '12'),
 array( 'name' => 'Cheruthazham', 'state_id' => '12'),
 array( 'name' => 'Chittur-Thathamangalam', 'state_id' => '12'),
 array( 'name' => 'Chockli', 'state_id' => '12'),
 array( 'name' => 'Erattupetta', 'state_id' => '12'),
 array( 'name' => 'Guruvayoor', 'state_id' => '12'),
 array( 'name' => 'Irinjalakuda', 'state_id' => '12'),
 array( 'name' => 'Kadirur', 'state_id' => '12'),
 array( 'name' => 'Kalliasseri', 'state_id' => '12'),
 array( 'name' => 'Kalpetta', 'state_id' => '12'),
 array( 'name' => 'Kanhangad', 'state_id' => '12'),
 array( 'name' => 'Kanjikkuzhi', 'state_id' => '12'),
 array( 'name' => 'Kannur', 'state_id' => '12'),
 array( 'name' => 'Kasaragod', 'state_id' => '12'),
 array( 'name' => 'Kayamkulam', 'state_id' => '12'),
 array( 'name' => 'Kochi', 'state_id' => '12'),
 array( 'name' => 'Kodungallur', 'state_id' => '12'),
 array( 'name' => 'Kollam', 'state_id' => '12'),
 array( 'name' => 'Koothuparamba', 'state_id' => '12'),
 array( 'name' => 'Kothamangalam', 'state_id' => '12'),
 array( 'name' => 'Kottayam', 'state_id' => '12'),
 array( 'name' => 'Kozhikode', 'state_id' => '12'),
 array( 'name' => 'Kunnamkulam', 'state_id' => '12'),
 array( 'name' => 'Malappuram', 'state_id' => '12'),
 array( 'name' => 'Mattannur', 'state_id' => '12'),
 array( 'name' => 'Mavelikkara', 'state_id' => '12'),
 array( 'name' => 'Mavoor', 'state_id' => '12'),
 array( 'name' => 'Muvattupuzha', 'state_id' => '12'),
 array( 'name' => 'Nedumangad', 'state_id' => '12'),
 array( 'name' => 'Neyyattinkara', 'state_id' => '12'),
 array( 'name' => 'Ottappalam', 'state_id' => '12'),
 array( 'name' => 'Palai', 'state_id' => '12'),
 array( 'name' => 'Palakkad', 'state_id' => '12'),
 array( 'name' => 'Panniyannur', 'state_id' => '12'),
 array( 'name' => 'Pappinisseri', 'state_id' => '12'),
 array( 'name' => 'Paravoor', 'state_id' => '12'),
 array( 'name' => 'Pathanamthitta', 'state_id' => '12'),
 array( 'name' => 'Payyannur', 'state_id' => '12'),
 array( 'name' => 'Peringathur', 'state_id' => '12'),
 array( 'name' => 'Perinthalmanna', 'state_id' => '12'),
 array( 'name' => 'Perumbavoor', 'state_id' => '12'),
 array( 'name' => 'Ponnani', 'state_id' => '12'),
 array( 'name' => 'Punalur', 'state_id' => '12'),
 array( 'name' => 'Quilandy', 'state_id' => '12'),
 array( 'name' => 'Shoranur', 'state_id' => '12'),
 array( 'name' => 'Taliparamba', 'state_id' => '12'),
 array( 'name' => 'Thiruvalla', 'state_id' => '12'),
 array( 'name' => 'Thiruvananthapuram', 'state_id' => '12'),
 array( 'name' => 'Thodupuzha', 'state_id' => '12'),
 array( 'name' => 'Thrissur', 'state_id' => '12'),
 array( 'name' => 'Tirur', 'state_id' => '12'),
 array( 'name' => 'Vadakara', 'state_id' => '12'),
 array( 'name' => 'Vaikom', 'state_id' => '12'),
 array( 'name' => 'Varkala', 'state_id' => '12'),
 array( 'name' => 'Ashok Nagar', 'state_id' => '13'),
 array( 'name' => 'Balaghat', 'state_id' => '13'),
 array( 'name' => 'Betul', 'state_id' => '13'),
 array( 'name' => 'Bhopal', 'state_id' => '13'),
 array( 'name' => 'Burhanpur', 'state_id' => '13'),
 array( 'name' => 'Chhatarpur', 'state_id' => '13'),
 array( 'name' => 'Dabra', 'state_id' => '13'),
 array( 'name' => 'Datia', 'state_id' => '13'),
 array( 'name' => 'Dewas', 'state_id' => '13'),
 array( 'name' => 'Dhar', 'state_id' => '13'),
 array( 'name' => 'Fatehabad', 'state_id' => '13'),
 array( 'name' => 'Gwalior', 'state_id' => '13'),
 array( 'name' => 'Indore', 'state_id' => '13'),
 array( 'name' => 'Itarsi', 'state_id' => '13'),
 array( 'name' => 'Jabalpur', 'state_id' => '13'),
 array( 'name' => 'Katni', 'state_id' => '13'),
 array( 'name' => 'Kotma', 'state_id' => '13'),
 array( 'name' => 'Lahar', 'state_id' => '13'),
 array( 'name' => 'Lundi', 'state_id' => '13'),
 array( 'name' => 'Maharajpur', 'state_id' => '13'),
 array( 'name' => 'Mahidpur', 'state_id' => '13'),
 array( 'name' => 'Maihar', 'state_id' => '13'),
 array( 'name' => 'Malajkhand', 'state_id' => '13'),
 array( 'name' => 'Manasa', 'state_id' => '13'),
 array( 'name' => 'Manawar', 'state_id' => '13'),
 array( 'name' => 'Mandideep', 'state_id' => '13'),
 array( 'name' => 'Mandla', 'state_id' => '13'),
 array( 'name' => 'Mandsaur', 'state_id' => '13'),
 array( 'name' => 'Mauganj', 'state_id' => '13'),
 array( 'name' => 'Mhow Cantonment', 'state_id' => '13'),
 array( 'name' => 'Mhowgaon', 'state_id' => '13'),
 array( 'name' => 'Morena', 'state_id' => '13'),
 array( 'name' => 'Multai', 'state_id' => '13'),
 array( 'name' => 'Murwara', 'state_id' => '13'),
 array( 'name' => 'Nagda', 'state_id' => '13'),
 array( 'name' => 'Nainpur', 'state_id' => '13'),
 array( 'name' => 'Narsinghgarh', 'state_id' => '13'),
 array( 'name' => 'Narsinghgarh', 'state_id' => '13'),
 array( 'name' => 'Neemuch', 'state_id' => '13'),
 array( 'name' => 'Nepanagar', 'state_id' => '13'),
 array( 'name' => 'Niwari', 'state_id' => '13'),
 array( 'name' => 'Nowgong', 'state_id' => '13'),
 array( 'name' => 'Nowrozabad', 'state_id' => '13'),
 array( 'name' => 'Pachore', 'state_id' => '13'),
 array( 'name' => 'Pali', 'state_id' => '13'),
 array( 'name' => 'Panagar', 'state_id' => '13'),
 array( 'name' => 'Pandhurna', 'state_id' => '13'),
 array( 'name' => 'Panna', 'state_id' => '13'),
 array( 'name' => 'Pasan', 'state_id' => '13'),
 array( 'name' => 'Pipariya', 'state_id' => '13'),
 array( 'name' => 'Pithampur', 'state_id' => '13'),
 array( 'name' => 'Porsa', 'state_id' => '13'),
 array( 'name' => 'Prithvipur', 'state_id' => '13'),
 array( 'name' => 'Raghogarh-Vijaypur', 'state_id' => '13'),
 array( 'name' => 'Rahatgarh', 'state_id' => '13'),
 array( 'name' => 'Raisen', 'state_id' => '13'),
 array( 'name' => 'Rajgarh', 'state_id' => '13'),
 array( 'name' => 'Ratlam', 'state_id' => '13'),
 array( 'name' => 'Rau', 'state_id' => '13'),
 array( 'name' => 'Rehli', 'state_id' => '13'),
 array( 'name' => 'Rewa', 'state_id' => '13'),
 array( 'name' => 'Sabalgarh', 'state_id' => '13'),
 array( 'name' => 'Sagar', 'state_id' => '13'),
 array( 'name' => 'Sanawad', 'state_id' => '13'),
 array( 'name' => 'Sarangpur', 'state_id' => '13'),
 array( 'name' => 'Sarni', 'state_id' => '13'),
 array( 'name' => 'Satna', 'state_id' => '13'),
 array( 'name' => 'Sausar', 'state_id' => '13'),
 array( 'name' => 'Sehore', 'state_id' => '13'),
 array( 'name' => 'Sendhwa', 'state_id' => '13'),
 array( 'name' => 'Seoni', 'state_id' => '13'),
 array( 'name' => 'Seoni-Malwa', 'state_id' => '13'),
 array( 'name' => 'Shahdol', 'state_id' => '13'),
 array( 'name' => 'Shajapur', 'state_id' => '13'),
 array( 'name' => 'Shamgarh', 'state_id' => '13'),
 array( 'name' => 'Sheopur', 'state_id' => '13'),
 array( 'name' => 'Shivpuri', 'state_id' => '13'),
 array( 'name' => 'Shujalpur', 'state_id' => '13'),
 array( 'name' => 'Sidhi', 'state_id' => '13'),
 array( 'name' => 'Sihora', 'state_id' => '13'),
 array( 'name' => 'Singrauli', 'state_id' => '13'),
 array( 'name' => 'Sironj', 'state_id' => '13'),
 array( 'name' => 'Sohagpur', 'state_id' => '13'),
 array( 'name' => 'Tarana', 'state_id' => '13'),
 array( 'name' => 'Tikamgarh', 'state_id' => '13'),
 array( 'name' => 'Ujhani', 'state_id' => '13'),
 array( 'name' => 'Ujjain', 'state_id' => '13'),
 array( 'name' => 'Umaria', 'state_id' => '13'),
 array( 'name' => 'Vidisha', 'state_id' => '13'),
 array( 'name' => 'Wara Seoni', 'state_id' => '13'),
 array( 'name' => 'Ahmednagar', 'state_id' => '14'),
 array( 'name' => 'Akola', 'state_id' => '14'),
 array( 'name' => 'Amravati', 'state_id' => '14'),
 array( 'name' => 'Aurangabad', 'state_id' => '14'),
 array( 'name' => 'Baramati', 'state_id' => '14'),
 array( 'name' => 'Chalisgaon', 'state_id' => '14'),
 array( 'name' => 'Chinchani', 'state_id' => '14'),
 array( 'name' => 'Devgarh', 'state_id' => '14'),
 array( 'name' => 'Dhule', 'state_id' => '14'),
 array( 'name' => 'Dombivli', 'state_id' => '14'),
 array( 'name' => 'Durgapur', 'state_id' => '14'),
 array( 'name' => 'Ichalkaranji', 'state_id' => '14'),
 array( 'name' => 'Jalna', 'state_id' => '14'),
 array( 'name' => 'Kalyan', 'state_id' => '14'),
 array('name' => 'Kolhapur', 'state_id' => '14'),
 array( 'name' => 'Latur', 'state_id' => '14'),
 array( 'name' => 'Loha', 'state_id' => '14'),
 array( 'name' => 'Lonar', 'state_id' => '14'),
 array( 'name' => 'Lonavla', 'state_id' => '14'),
 array( 'name' => 'Mahad', 'state_id' => '14'),
 array( 'name' => 'Mahuli', 'state_id' => '14'),
 array( 'name' => 'Malegaon', 'state_id' => '14'),
 array( 'name' => 'Malkapur', 'state_id' => '14'),
 array( 'name' => 'Manchar', 'state_id' => '14'),
 array( 'name' => 'Mangalvedhe', 'state_id' => '14'),
 array( 'name' => 'Mangrulpir', 'state_id' => '14'),
 array( 'name' => 'Manjlegaon', 'state_id' => '14'),
 array( 'name' => 'Manmad', 'state_id' => '14'),
 array( 'name' => 'Manwath', 'state_id' => '14'),
 array( 'name' => 'Mehkar', 'state_id' => '14'),
 array( 'name' => 'Mhaswad', 'state_id' => '14'),
 array( 'name' => 'Miraj', 'state_id' => '14'),
 array( 'name' => 'Morshi', 'state_id' => '14'),
 array( 'name' => 'Mukhed', 'state_id' => '14'),
 array( 'name' => 'Mul', 'state_id' => '14'),
 array( 'name' => 'Mumbai', 'state_id' => '14'),
 array( 'name' => 'Murtijapur', 'state_id' => '14'),
 array( 'name' => 'Nagpur', 'state_id' => '14'),
 array( 'name' => 'Nalasopara', 'state_id' => '14'),
 array( 'name' => 'Nanded-Waghala', 'state_id' => '14'),
 array( 'name' => 'Nandgaon', 'state_id' => '14'),
 array( 'name' => 'Nandura', 'state_id' => '14'),
 array( 'name' => 'Nandurbar', 'state_id' => '14'),
 array( 'name' => 'Narkhed', 'state_id' => '14'),
 array( 'name' => 'Nashik', 'state_id' => '14'),
 array( 'name' => 'Navi Mumbai', 'state_id' => '14'),
 array( 'name' => 'Nawapur', 'state_id' => '14'),
 array( 'name' => 'Nilanga', 'state_id' => '14'),
 array( 'name' => 'Osmanabad', 'state_id' => '14'),
 array( 'name' => 'Ozar', 'state_id' => '14'),
 array( 'name' => 'Pachora', 'state_id' => '14'),
 array( 'name' => 'Paithan', 'state_id' => '14'),
 array( 'name' => 'Palghar', 'state_id' => '14'),
 array( 'name' => 'Pandharkaoda', 'state_id' => '14'),
 array( 'name' => 'Pandharpur', 'state_id' => '14'),
 array( 'name' => 'Panvel', 'state_id' => '14'),
 array( 'name' => 'Parbhani', 'state_id' => '14'),
 array( 'name' => 'Parli', 'state_id' => '14'),
 array( 'name' => 'Parola', 'state_id' => '14'),
 array( 'name' => 'Partur', 'state_id' => '14'),
 array( 'name' => 'Pathardi', 'state_id' => '14'),
 array( 'name' => 'Pathri', 'state_id' => '14'),
 array( 'name' => 'Patur', 'state_id' => '14'),
 array( 'name' => 'Pauni', 'state_id' => '14'),
 array( 'name' => 'Pen', 'state_id' => '14'),
 array( 'name' => 'Phaltan', 'state_id' => '14'),
 array( 'name' => 'Pulgaon', 'state_id' => '14'),
 array( 'name' => 'Pune', 'state_id' => '14'),
 array( 'name' => 'Purna', 'state_id' => '14'),
 array( 'name' => 'Pusad', 'state_id' => '14'),
 array( 'name' => 'Rahuri', 'state_id' => '14'),
 array( 'name' => 'Rajura', 'state_id' => '14'),
 array( 'name' => 'Ramtek', 'state_id' => '14'),
 array( 'name' => 'Ratnagiri', 'state_id' => '14'),
 array( 'name' => 'Raver', 'state_id' => '14'),
 array( 'name' => 'Risod', 'state_id' => '14'),
 array( 'name' => 'Sailu', 'state_id' => '14'),
 array( 'name' => 'Sangamner', 'state_id' => '14'),
 array( 'name' => 'Sangli', 'state_id' => '14'),
 array( 'name' => 'Sangole', 'state_id' => '14'),
 array( 'name' => 'Sasvad', 'state_id' => '14'),
 array( 'name' => 'Satana', 'state_id' => '14'),
 array( 'name' => 'Satara', 'state_id' => '14'),
 array( 'name' => 'Savner', 'state_id' => '14'),
 array( 'name' => 'Sawantwadi', 'state_id' => '14'),
 array( 'name' => 'Shahade', 'state_id' => '14'),
 array( 'name' => 'Shegaon', 'state_id' => '14'),
 array( 'name' => 'Shendurjana', 'state_id' => '14'),
 array( 'name' => 'Shirdi', 'state_id' => '14'),
 array( 'name' => 'Shirpur-Warwade', 'state_id' => '14'),
 array( 'name' => 'Shirur', 'state_id' => '14'),
 array( 'name' => 'Shrigonda', 'state_id' => '14'),
 array( 'name' => 'Shrirampur', 'state_id' => '14'),
 array( 'name' => 'Sillod', 'state_id' => '14'),
 array( 'name' => 'Sinnar', 'state_id' => '14'),
 array( 'name' => 'Solapur', 'state_id' => '14'),
 array( 'name' => 'Soyagaon', 'state_id' => '14'),
 array( 'name' => 'Talegaon Dabhade', 'state_id' => '14'),
 array( 'name' => 'Talode', 'state_id' => '14'),
 array( 'name' => 'Tasgaon', 'state_id' => '14'),
 array( 'name' => 'Tirora', 'state_id' => '14'),
 array( 'name' => 'Tuljapur', 'state_id' => '14'),
 array( 'name' => 'Tumsar', 'state_id' => '14'),
 array( 'name' => 'Uran', 'state_id' => '14'),
 array( 'name' => 'Uran Islampur', 'state_id' => '14'),
 array( 'name' => 'Wadgaon Road', 'state_id' => '14'),
 array( 'name' => 'Wai', 'state_id' => '14'),
 array( 'name' => 'Wani', 'state_id' => '14'),
 array( 'name' => 'Wardha', 'state_id' => '14'),
 array( 'name' => 'Warora', 'state_id' => '14'),
 array( 'name' => 'Warud', 'state_id' => '14'),
 array( 'name' => 'Washim', 'state_id' => '14'),
 array( 'name' => 'Yevla', 'state_id' => '14'),
 array( 'name' => 'Uchgaon', 'state_id' => '14'),
 array( 'name' => 'Udgir', 'state_id' => '14'),
 array( 'name' => 'Umarga', 'state_id' => '14'),
 array( 'name' => 'Umarkhed', 'state_id' => '14'),
 array( 'name' => 'Umred', 'state_id' => '14'),
 array( 'name' => 'Vadgaon Kasba', 'state_id' => '14'),
 array( 'name' => 'Vaijapur', 'state_id' => '14'),
 array( 'name' => 'Vasai', 'state_id' => '14'),
 array( 'name' => 'Virar', 'state_id' => '14'),
 array( 'name' => 'Vita', 'state_id' => '14'),
 array( 'name' => 'Yavatmal', 'state_id' => '14'),
 array( 'name' => 'Yawal', 'state_id' => '14'),
 array( 'name' => 'Imphal', 'state_id' => '15'),
 array( 'name' => 'Kakching', 'state_id' => '15'),
 array( 'name' => 'Lilong', 'state_id' => '15'),
 array( 'name' => 'Mayang Imphal', 'state_id' => '15'),
 array( 'name' => 'Thoubal', 'state_id' => '15'),
 array( 'name' => 'Jowai', 'state_id' => '16'),
 array( 'name' => 'Nongstoin', 'state_id' => '16'),
 array( 'name' => 'Shillong', 'state_id' => '16'),
 array( 'name' => 'Tura', 'state_id' => '16'),
 array( 'name' => 'Aizawl', 'state_id' => '17'),
 array( 'name' => 'Champhai', 'state_id' => '17'),
 array( 'name' => 'Lunglei', 'state_id' => '17'),
 array( 'name' => 'Saiha', 'state_id' => '17'),
 array( 'name' => 'Dimapur', 'state_id' => '18'),
 array( 'name' => 'Kohima', 'state_id' => '18'),
 array( 'name' => 'Mokokchung', 'state_id' => '18'),
 array( 'name' => 'Tuensang', 'state_id' => '18'),
 array( 'name' => 'Wokha', 'state_id' => '18'),
 array( 'name' => 'Zunheboto', 'state_id' => '18'),
 array( 'name' => 'Anandapur', 'state_id' => '19'),
 array( 'name' => 'Anugul', 'state_id' => '19'),
 array( 'name' => 'Asika', 'state_id' => '19'),
 array( 'name' => 'Balangir', 'state_id' => '19'),
 array( 'name' => 'Balasore', 'state_id' => '19'),
 array( 'name' => 'Baleshwar', 'state_id' => '19'),
 array( 'name' => 'Bamra', 'state_id' => '19'),
 array( 'name' => 'Barbil', 'state_id' => '19'),
 array( 'name' => 'Bargarh', 'state_id' => '19'),
 array( 'name' => 'Bargarh', 'state_id' => '19'),
 array( 'name' => 'Baripada', 'state_id' => '19'),
 array( 'name' => 'Basudebpur', 'state_id' => '19'),
 array( 'name' => 'Belpahar', 'state_id' => '19'),
 array( 'name' => 'Bhadrak', 'state_id' => '19'),
 array( 'name' => 'Bhawanipatna', 'state_id' => '19'),
 array( 'name' => 'Bhuban', 'state_id' => '19'),
 array( 'name' => 'Bhubaneswar', 'state_id' => '19'),
 array( 'name' => 'Biramitrapur', 'state_id' => '19'),
 array( 'name' => 'Brahmapur', 'state_id' => '19'),
 array( 'name' => 'Brajrajnagar', 'state_id' => '19'),
 array( 'name' => 'Byasanagar', 'state_id' => '19'),
 array( 'name' => 'Cuttack', 'state_id' => '19'),
 array( 'name' => 'Debagarh', 'state_id' => '19'),
 array( 'name' => 'Dhenkanal', 'state_id' => '19'),
 array( 'name' => 'Gunupur', 'state_id' => '19'),
 array( 'name' => 'Hinjilicut', 'state_id' => '19'),
 array( 'name' => 'Jagatsinghapur', 'state_id' => '19'),
 array( 'name' => 'Jajapur', 'state_id' => '19'),
 array( 'name' => 'Jaleswar', 'state_id' => '19'),
 array( 'name' => 'Jatani', 'state_id' => '19'),
 array( 'name' => 'Jeypur', 'state_id' => '19'),
 array( 'name' => 'Jharsuguda', 'state_id' => '19'),
 array( 'name' => 'Joda', 'state_id' => '19'),
 array( 'name' => 'Kantabanji', 'state_id' => '19'),
 array( 'name' => 'Karanjia', 'state_id' => '19'),
 array( 'name' => 'Kendrapara', 'state_id' => '19'),
 array( 'name' => 'Kendujhar', 'state_id' => '19'),
 array( 'name' => 'Khordha', 'state_id' => '19'),
 array( 'name' => 'Koraput', 'state_id' => '19'),
 array( 'name' => 'Malkangiri', 'state_id' => '19'),
 array( 'name' => 'Nabarangapur', 'state_id' => '19'),
 array( 'name' => 'Paradip', 'state_id' => '19'),
 array( 'name' => 'Parlakhemundi', 'state_id' => '19'),
 array( 'name' => 'Pattamundai', 'state_id' => '19'),
 array( 'name' => 'Phulabani', 'state_id' => '19'),
 array( 'name' => 'Puri', 'state_id' => '19'),
 array( 'name' => 'Rairangpur', 'state_id' => '19'),
 array( 'name' => 'Rajagangapur', 'state_id' => '19'),
 array( 'name' => 'Raurkela', 'state_id' => '19'),
 array( 'name' => 'Rayagada', 'state_id' => '19'),
 array( 'name' => 'Sambalpur', 'state_id' => '19'),
 array( 'name' => 'Soro', 'state_id' => '19'),
 array( 'name' => 'Sunabeda', 'state_id' => '19'),
 array( 'name' => 'Sundargarh', 'state_id' => '19'),
 array( 'name' => 'Talcher', 'state_id' => '19'),
 array( 'name' => 'Titlagarh', 'state_id' => '19'),
 array( 'name' => 'Umarkote', 'state_id' => '19'),
 array( 'name' => 'Ahmedgarh', 'state_id' => '20'),
 array( 'name' => 'Amritsar', 'state_id' => '20'),
 array( 'name' => 'Barnala', 'state_id' => '20'),
 array( 'name' => 'Batala', 'state_id' => '20'),
 array( 'name' => 'Bathinda', 'state_id' => '20'),
 array( 'name' => 'Bhagha Purana', 'state_id' => '20'),
 array( 'name' => 'Budhlada', 'state_id' => '20'),
 array( 'name' => 'Chandigarh', 'state_id' => '20'),
 array( 'name' => 'Dasua', 'state_id' => '20'),
 array( 'name' => 'Dhuri', 'state_id' => '20'),
 array( 'name' => 'Dinanagar', 'state_id' => '20'),
 array( 'name' => 'Faridkot', 'state_id' => '20'),
 array( 'name' => 'Fazilka', 'state_id' => '20'),
 array( 'name' => 'Firozpur', 'state_id' => '20'),
 array( 'name' => 'Firozpur Cantt.', 'state_id' => '20'),
 array( 'name' => 'Giddarbaha', 'state_id' => '20'),
 array( 'name' => 'Gobindgarh', 'state_id' => '20'),
 array( 'name' => 'Gurdaspur', 'state_id' => '20'),
 array( 'name' => 'Hoshiarpur', 'state_id' => '20'),
 array( 'name' => 'Jagraon', 'state_id' => '20'),
 array( 'name' => 'Jaitu', 'state_id' => '20'),
 array( 'name' => 'Jalalabad', 'state_id' => '20'),
 array( 'name' => 'Jalandhar', 'state_id' => '20'),
 array( 'name' => 'Jalandhar Cantt.', 'state_id' => '20'),
 array( 'name' => 'Jandiala', 'state_id' => '20'),
 array( 'name' => 'Kapurthala', 'state_id' => '20'),
 array( 'name' => 'Karoran', 'state_id' => '20'),
 array( 'name' => 'Kartarpur', 'state_id' => '20'),
 array( 'name' => 'Khanna', 'state_id' => '20'),
 array( 'name' => 'Kharar', 'state_id' => '20'),
 array( 'name' => 'Kot Kapura', 'state_id' => '20'),
 array( 'name' => 'Kurali', 'state_id' => '20'),
 array( 'name' => 'Longowal', 'state_id' => '20'),
 array( 'name' => 'Ludhiana', 'state_id' => '20'),
 array( 'name' => 'Malerkotla', 'state_id' => '20'),
 array( 'name' => 'Malout', 'state_id' => '20'),
 array( 'name' => 'Mansa', 'state_id' => '20'),
 array( 'name' => 'Maur', 'state_id' => '20'),
 array( 'name' => 'Moga', 'state_id' => '20'),
 array( 'name' => 'Mohali', 'state_id' => '20'),
 array( 'name' => 'Morinda', 'state_id' => '20'),
 array( 'name' => 'Mukerian', 'state_id' => '20'),
 array( 'name' => 'Muktsar', 'state_id' => '20'),
 array( 'name' => 'Nabha', 'state_id' => '20'),
 array( 'name' => 'Nakodar', 'state_id' => '20'),
 array( 'name' => 'Nangal', 'state_id' => '20'),
 array( 'name' => 'Nawanshahr', 'state_id' => '20'),
 array( 'name' => 'Pathankot', 'state_id' => '20'),
 array( 'name' => 'Patiala', 'state_id' => '20'),
 array( 'name' => 'Patran', 'state_id' => '20'),
 array( 'name' => 'Patti', 'state_id' => '20'),
 array( 'name' => 'Phagwara', 'state_id' => '20'),
 array( 'name' => 'Phillaur', 'state_id' => '20'),
 array( 'name' => 'Qadian', 'state_id' => '20'),
 array( 'name' => 'Raikot', 'state_id' => '20'),
 array( 'name' => 'Rajpura', 'state_id' => '20'),
 array( 'name' => 'Rampura Phul', 'state_id' => '20'),
 array( 'name' => 'Rupnagar', 'state_id' => '20'),
 array( 'name' => 'Samana', 'state_id' => '20'),
 array( 'name' => 'Sangrur', 'state_id' => '20'),
 array( 'name' => 'Sirhind Fatehgarh Sahib', 'state_id' => '20'),
 array( 'name' => 'Sujanpur', 'state_id' => '20'),
 array( 'name' => 'Sunam', 'state_id' => '20'),
 array( 'name' => 'Talwara', 'state_id' => '20'),
 array( 'name' => 'Tarn Taran', 'state_id' => '20'),
 array( 'name' => 'Urmar Tanda', 'state_id' => '20'),
 array( 'name' => 'Zira', 'state_id' => '20'),
 array( 'name' => 'Zirakpur', 'state_id' => '20'),
 array( 'name' => 'Bali', 'state_id' => '21'),
 array( 'name' => 'Banswara', 'state_id' => '21'),
 array( 'name' => 'Ajmer', 'state_id' => '21'),
 array( 'name' => 'Alwar', 'state_id' => '21'),
 array( 'name' => 'Bandikui', 'state_id' => '21'),
 array( 'name' => 'Baran', 'state_id' => '21'),
 array( 'name' => 'Barmer', 'state_id' => '21'),
 array( 'name' => 'Bikaner', 'state_id' => '21'),
 array( 'name' => 'Fatehpur', 'state_id' => '21'),
 array( 'name' => 'Jaipur', 'state_id' => '21'),
 array( 'name' => 'Jaisalmer', 'state_id' => '21'),
 array( 'name' => 'Jodhpur', 'state_id' => '21'),
 array( 'name' => 'Kota', 'state_id' => '21'),
 array( 'name' => 'Lachhmangarh', 'state_id' => '21'),
 array( 'name' => 'Ladnu', 'state_id' => '21'),
 array( 'name' => 'Lakheri', 'state_id' => '21'),
 array( 'name' => 'Lalsot', 'state_id' => '21'),
 array( 'name' => 'Losal', 'state_id' => '21'),
 array( 'name' => 'Makrana', 'state_id' => '21'),
 array( 'name' => 'Malpura', 'state_id' => '21'),
 array( 'name' => 'Mandalgarh', 'state_id' => '21'),
 array( 'name' => 'Mandawa', 'state_id' => '21'),
 array( 'name' => 'Mangrol', 'state_id' => '21'),
 array( 'name' => 'Merta City', 'state_id' => '21'),
 array( 'name' => 'Mount Abu', 'state_id' => '21'),
 array( 'name' => 'Nadbai', 'state_id' => '21'),
 array( 'name' => 'Nagar', 'state_id' => '21'),
 array( 'name' => 'Nagaur', 'state_id' => '21'),
 array( 'name' => 'Nargund', 'state_id' => '21'),
 array( 'name' => 'Nasirabad', 'state_id' => '21'),
 array( 'name' => 'Nathdwara', 'state_id' => '21'),
 array( 'name' => 'Navalgund', 'state_id' => '21'),
 array( 'name' => 'Nawalgarh', 'state_id' => '21'),
 array( 'name' => 'Neem-Ka-Thana', 'state_id' => '21'),
 array( 'name' => 'Nelamangala', 'state_id' => '21'),
 array( 'name' => 'Nimbahera', 'state_id' => '21'),
 array( 'name' => 'Nipani', 'state_id' => '21'),
 array( 'name' => 'Niwai', 'state_id' => '21'),
 array( 'name' => 'Nohar', 'state_id' => '21'),
 array( 'name' => 'Nokha', 'state_id' => '21'),
 array( 'name' => 'Pali', 'state_id' => '21'),
 array( 'name' => 'Phalodi', 'state_id' => '21'),
 array( 'name' => 'Phulera', 'state_id' => '21'),
 array( 'name' => 'Pilani', 'state_id' => '21'),
 array( 'name' => 'Pilibanga', 'state_id' => '21'),
 array( 'name' => 'Pindwara', 'state_id' => '21'),
 array( 'name' => 'Pipar City', 'state_id' => '21'),
 array( 'name' => 'Prantij', 'state_id' => '21'),
 array( 'name' => 'Pratapgarh', 'state_id' => '21'),
 array( 'name' => 'Raisinghnagar', 'state_id' => '21'),
 array( 'name' => 'Rajakhera', 'state_id' => '21'),
 array( 'name' => 'Rajaldesar', 'state_id' => '21'),
 array( 'name' => 'Rajgarh (Alwar)', 'state_id' => '21'),
 array( 'name' => 'Rajgarh (Churu', 'state_id' => '21'),
 array( 'name' => 'Rajsamand', 'state_id' => '21'),
 array( 'name' => 'Ramganj Mandi', 'state_id' => '21'),
 array( 'name' => 'Ramngarh', 'state_id' => '21'),
 array( 'name' => 'Ratangarh', 'state_id' => '21'),
 array( 'name' => 'Rawatbhata', 'state_id' => '21'),
 array( 'name' => 'Rawatsar', 'state_id' => '21'),
 array( 'name' => 'Reengus', 'state_id' => '21'),
 array( 'name' => 'Sadri', 'state_id' => '21'),
 array( 'name' => 'Sadulshahar', 'state_id' => '21'),
 array( 'name' => 'Sagwara', 'state_id' => '21'),
 array( 'name' => 'Sambhar', 'state_id' => '21'),
 array( 'name' => 'Sanchore', 'state_id' => '21'),
 array( 'name' => 'Sangaria', 'state_id' => '21'),
 array( 'name' => 'Sardarshahar', 'state_id' => '21'),
 array( 'name' => 'Sawai Madhopur', 'state_id' => '21'),
 array( 'name' => 'Shahpura', 'state_id' => '21'),
 array( 'name' => 'Shahpura', 'state_id' => '21'),
 array( 'name' => 'Sheoganj', 'state_id' => '21'),
 array( 'name' => 'Sikar', 'state_id' => '21'),
 array( 'name' => 'Sirohi', 'state_id' => '21'),
 array( 'name' => 'Sojat', 'state_id' => '21'),
 array( 'name' => 'Sri Madhopur', 'state_id' => '21'),
 array( 'name' => 'Sujangarh', 'state_id' => '21'),
 array( 'name' => 'Sumerpur', 'state_id' => '21'),
 array( 'name' => 'Suratgarh', 'state_id' => '21'),
 array( 'name' => 'Taranagar', 'state_id' => '21'),
 array( 'name' => 'Todabhim', 'state_id' => '21'),
 array( 'name' => 'Todaraisingh', 'state_id' => '21'),
 array( 'name' => 'Tonk', 'state_id' => '21'),
 array( 'name' => 'Udaipur', 'state_id' => '21'),
 array( 'name' => 'Udaipurwati', 'state_id' => '21'),
 array( 'name' => 'Vijainagar', 'state_id' => '21'),
 array( 'name' => 'Gangtok', 'state_id' => '22'),
 array( 'name' => 'Calcutta', 'state_id' => '28'),
 array( 'name' => 'Arakkonam', 'state_id' => '23'),
 array( 'name' => 'Arcot', 'state_id' => '23'),
 array( 'name' => 'Ariyalur', 'state_id' => '23'),
 array( 'name' => 'Aruppukkottai', 'state_id' => '23'),
 array( 'name' => 'Bhavani', 'state_id' => '23'),
 array( 'name' => 'Chengalpattu', 'state_id' => '23'),
 array( 'name' => 'Chennai', 'state_id' => '23'),
 array( 'name' => 'Chinna salem', 'state_id' => '23'),
 array( 'name' => 'Coimbatore', 'state_id' => '23'),
 array( 'name' => 'Coonoor', 'state_id' => '23'),
 array( 'name' => 'Cuddalore', 'state_id' => '23'),
 array( 'name' => 'Dharmapuri', 'state_id' => '23'),
 array( 'name' => 'Dindigul', 'state_id' => '23'),
 array( 'name' => 'Erode', 'state_id' => '23'),
 array( 'name' => 'Gudalur', 'state_id' => '23'),
 array( 'name' => 'Gudalur', 'state_id' => '23'),
 array( 'name' => 'Gudalur', 'state_id' => '23'),
 array( 'name' => 'Kanchipuram', 'state_id' => '23'),
 array( 'name' => 'Karaikudi', 'state_id' => '23'),
 array( 'name' => 'Karungal', 'state_id' => '23'),
 array( 'name' => 'Karur', 'state_id' => '23'),
 array( 'name' => 'Kollankodu', 'state_id' => '23'),
 array( 'name' => 'Lalgudi', 'state_id' => '23'),
 array( 'name' => 'Madurai', 'state_id' => '23'),
 array( 'name' => 'Nagapattinam', 'state_id' => '23'),
 array( 'name' => 'Nagercoil', 'state_id' => '23'),
 array( 'name' => 'Namagiripettai', 'state_id' => '23'),
 array( 'name' => 'Namakkal', 'state_id' => '23'),
 array( 'name' => 'Nandivaram-Guduvancheri', 'state_id' => '23'),
 array( 'name' => 'Nanjikottai', 'state_id' => '23'),
 array( 'name' => 'Natham', 'state_id' => '23'),
 array( 'name' => 'Nellikuppam', 'state_id' => '23'),
 array( 'name' => 'Neyveli', 'state_id' => '23'),
 array( 'name' => 'O\' Valley', 'state_id' => '23'),
 array( 'name' => 'Oddanchatram', 'state_id' => '23'),
 array( 'name' => 'P.N.Patti', 'state_id' => '23'),
 array( 'name' => 'Pacode', 'state_id' => '23'),
 array( 'name' => 'Padmanabhapuram', 'state_id' => '23'),
 array( 'name' => 'Palani', 'state_id' => '23'),
 array( 'name' => 'Palladam', 'state_id' => '23'),
 array( 'name' => 'Pallapatti', 'state_id' => '23'),
 array( 'name' => 'Pallikonda', 'state_id' => '23'),
 array( 'name' => 'Panagudi', 'state_id' => '23'),
 array( 'name' => 'Panruti', 'state_id' => '23'),
 array( 'name' => 'Paramakudi', 'state_id' => '23'),
 array( 'name' => 'Parangipettai', 'state_id' => '23'),
 array( 'name' => 'Pattukkottai', 'state_id' => '23'),
 array( 'name' => 'Perambalur', 'state_id' => '23'),
 array( 'name' => 'Peravurani', 'state_id' => '23'),
 array( 'name' => 'Periyakulam', 'state_id' => '23'),
 array( 'name' => 'Periyasemur', 'state_id' => '23'),
 array( 'name' => 'Pernampattu', 'state_id' => '23'),
 array( 'name' => 'Pollachi', 'state_id' => '23'),
 array( 'name' => 'Polur', 'state_id' => '23'),
 array( 'name' => 'Ponneri', 'state_id' => '23'),
 array( 'name' => 'Pudukkottai', 'state_id' => '23'),
 array( 'name' => 'Pudupattinam', 'state_id' => '23'),
 array( 'name' => 'Puliyankudi', 'state_id' => '23'),
 array( 'name' => 'Punjaipugalur', 'state_id' => '23'),
 array( 'name' => 'Rajapalayam', 'state_id' => '23'),
 array( 'name' => 'Ramanathapuram', 'state_id' => '23'),
 array( 'name' => 'Rameshwaram', 'state_id' => '23'),
 array( 'name' => 'Rasipuram', 'state_id' => '23'),
 array( 'name' => 'Salem', 'state_id' => '23'),
 array( 'name' => 'Sankarankoil', 'state_id' => '23'),
 array( 'name' => 'Sankari', 'state_id' => '23'),
 array( 'name' => 'Sathyamangalam', 'state_id' => '23'),
 array( 'name' => 'Sattur', 'state_id' => '23'),
 array( 'name' => 'Shenkottai', 'state_id' => '23'),
 array( 'name' => 'Sholavandan', 'state_id' => '23'),
 array( 'name' => 'Sholingur', 'state_id' => '23'),
 array( 'name' => 'Sirkali', 'state_id' => '23'),
 array( 'name' => 'Sivaganga', 'state_id' => '23'),
 array( 'name' => 'Sivagiri', 'state_id' => '23'),
 array( 'name' => 'Sivakasi', 'state_id' => '23'),
 array( 'name' => 'Srivilliputhur', 'state_id' => '23'),
 array( 'name' => 'Surandai', 'state_id' => '23'),
 array( 'name' => 'Suriyampalayam', 'state_id' => '23'),
 array( 'name' => 'Tenkasi', 'state_id' => '23'),
 array( 'name' => 'Thammampatti', 'state_id' => '23'),
 array( 'name' => 'Thanjavur', 'state_id' => '23'),
 array( 'name' => 'Tharamangalam', 'state_id' => '23'),
 array( 'name' => 'Tharangambadi', 'state_id' => '23'),
 array( 'name' => 'Theni Allinagaram', 'state_id' => '23'),
 array( 'name' => 'Thirumangalam', 'state_id' => '23'),
 array( 'name' => 'Thirunindravur', 'state_id' => '23'),
 array( 'name' => 'Thiruparappu', 'state_id' => '23'),
 array( 'name' => 'Thirupuvanam', 'state_id' => '23'),
 array( 'name' => 'Thiruthuraipoondi', 'state_id' => '23'),
 array( 'name' => 'Thiruvallur', 'state_id' => '23'),
 array( 'name' => 'Thiruvarur', 'state_id' => '23'),
 array( 'name' => 'Thoothukudi', 'state_id' => '23'),
 array( 'name' => 'Thuraiyur', 'state_id' => '23'),
 array( 'name' => 'Tindivanam', 'state_id' => '23'),
 array( 'name' => 'Tiruchendur', 'state_id' => '23'),
 array( 'name' => 'Tiruchengode', 'state_id' => '23'),
 array( 'name' => 'Tiruchirappalli', 'state_id' => '23'),
 array( 'name' => 'Tirukalukundram', 'state_id' => '23'),
 array( 'name' => 'Tirukkoyilur', 'state_id' => '23'),
 array( 'name' => 'Tirunelveli', 'state_id' => '23'),
 array( 'name' => 'Tirupathur', 'state_id' => '23'),
 array( 'name' => 'Tirupathur', 'state_id' => '23'),
 array( 'name' => 'Tiruppur', 'state_id' => '23'),
 array( 'name' => 'Tiruttani', 'state_id' => '23'),
 array( 'name' => 'Tiruvannamalai', 'state_id' => '23'),
 array( 'name' => 'Tiruvethipuram', 'state_id' => '23'),
 array( 'name' => 'Tittakudi', 'state_id' => '23'),
 array( 'name' => 'Udhagamandalam', 'state_id' => '23'),
 array( 'name' => 'Udumalaipettai', 'state_id' => '23'),
 array( 'name' => 'Unnamalaikadai', 'state_id' => '23'),
 array( 'name' => 'Usilampatti', 'state_id' => '23'),
 array( 'name' => 'Uthamapalayam', 'state_id' => '23'),
 array( 'name' => 'Uthiramerur', 'state_id' => '23'),
 array( 'name' => 'Vadakkuvalliyur', 'state_id' => '23'),
 array( 'name' => 'Vadalur', 'state_id' => '23'),
 array( 'name' => 'Vadipatti', 'state_id' => '23'),
 array( 'name' => 'Valparai', 'state_id' => '23'),
 array( 'name' => 'Vandavasi', 'state_id' => '23'),
 array( 'name' => 'Vaniyambadi', 'state_id' => '23'),
 array( 'name' => 'Vedaranyam', 'state_id' => '23'),
 array( 'name' => 'Vellakoil', 'state_id' => '23'),
 array( 'name' => 'Vellore', 'state_id' => '23'),
 array( 'name' => 'Vikramasingapuram', 'state_id' => '23'),
 array( 'name' => 'Viluppuram', 'state_id' => '23'),
 array( 'name' => 'Virudhachalam', 'state_id' => '23'),
 array( 'name' => 'Virudhunagar', 'state_id' => '23'),
 array( 'name' => 'Viswanatham', 'state_id' => '23'),
 array( 'name' => 'Agartala', 'state_id' => '25'),
 array( 'name' => 'Badharghat', 'state_id' => '25'),
 array( 'name' => 'Dharmanagar', 'state_id' => '25'),
 array( 'name' => 'Indranagar', 'state_id' => '25'),
 array( 'name' => 'Jogendranagar', 'state_id' => '25'),
 array( 'name' => 'Kailasahar', 'state_id' => '25'),
 array( 'name' => 'Khowai', 'state_id' => '25'),
 array( 'name' => 'Pratapgarh', 'state_id' => '25'),
 array( 'name' => 'Udaipur', 'state_id' => '25'),
 array( 'name' => 'Achhnera', 'state_id' => '26'),
 array( 'name' => 'Adari', 'state_id' => '26'),
 array( 'name' => 'Agra', 'state_id' => '26'),
 array( 'name' => 'Aligarh', 'state_id' => '26'),
 array( 'name' => 'Allahabad', 'state_id' => '26'),
 array( 'name' => 'Amroha', 'state_id' => '26'),
 array( 'name' => 'Azamgarh', 'state_id' => '26'),
 array( 'name' => 'Bahraich', 'state_id' => '26'),
 array( 'name' => 'Ballia', 'state_id' => '26'),
 array( 'name' => 'Balrampur', 'state_id' => '26'),
 array( 'name' => 'Banda', 'state_id' => '26'),
 array( 'name' => 'Bareilly', 'state_id' => '26'),
 array( 'name' => 'Chandausi', 'state_id' => '26'),
 array( 'name' => 'Dadri', 'state_id' => '26'),
 array( 'name' => 'Deoria', 'state_id' => '26'),
 array( 'name' => 'Etawah', 'state_id' => '26'),
 array( 'name' => 'Fatehabad', 'state_id' => '26'),
 array( 'name' => 'Fatehpur', 'state_id' => '26'),
 array( 'name' => 'Fatehpur', 'state_id' => '26'),
 array( 'name' => 'Greater Noida', 'state_id' => '26'),
 array( 'name' => 'Hamirpur', 'state_id' => '26'),
 array( 'name' => 'Hardoi', 'state_id' => '26'),
 array( 'name' => 'Jajmau', 'state_id' => '26'),
 array( 'name' => 'Jaunpur', 'state_id' => '26'),
 array( 'name' => 'Jhansi', 'state_id' => '26'),
 array( 'name' => 'Kalpi', 'state_id' => '26'),
 array( 'name' => 'Kanpur', 'state_id' => '26'),
 array( 'name' => 'Kota', 'state_id' => '26'),
 array( 'name' => 'Laharpur', 'state_id' => '26'),
 array( 'name' => 'Lakhimpur', 'state_id' => '26'),
 array( 'name' => 'Lal Gopalganj Nindaura', 'state_id' => '26'),
 array( 'name' => 'Lalganj', 'state_id' => '26'),
 array( 'name' => 'Lalitpur', 'state_id' => '26'),
 array( 'name' => 'Lar', 'state_id' => '26'),
 array( 'name' => 'Loni', 'state_id' => '26'),
 array( 'name' => 'Lucknow', 'state_id' => '26'),
 array( 'name' => 'Mathura', 'state_id' => '26'),
 array( 'name' => 'Meerut', 'state_id' => '26'),
 array( 'name' => 'Modinagar', 'state_id' => '26'),
 array( 'name' => 'Muradnagar', 'state_id' => '26'),
 array( 'name' => 'Nagina', 'state_id' => '26'),
 array( 'name' => 'Najibabad', 'state_id' => '26'),
 array( 'name' => 'Nakur', 'state_id' => '26'),
 array( 'name' => 'Nanpara', 'state_id' => '26'),
 array( 'name' => 'Naraura', 'state_id' => '26'),
 array( 'name' => 'Naugawan Sadat', 'state_id' => '26'),
 array( 'name' => 'Nautanwa', 'state_id' => '26'),
 array( 'name' => 'Nawabganj', 'state_id' => '26'),
 array( 'name' => 'Nehtaur', 'state_id' => '26'),
 array( 'name' => 'NOIDA', 'state_id' => '26'),
 array( 'name' => 'Noorpur', 'state_id' => '26'),
 array( 'name' => 'Obra', 'state_id' => '26'),
 array( 'name' => 'Orai', 'state_id' => '26'),
 array( 'name' => 'Padrauna', 'state_id' => '26'),
 array( 'name' => 'Palia Kalan', 'state_id' => '26'),
 array( 'name' => 'Parasi', 'state_id' => '26'),
 array( 'name' => 'Phulpur', 'state_id' => '26'),
 array( 'name' => 'Pihani', 'state_id' => '26'),
 array( 'name' => 'Pilibhit', 'state_id' => '26'),
 array( 'name' => 'Pilkhuwa', 'state_id' => '26'),
 array( 'name' => 'Powayan', 'state_id' => '26'),
 array( 'name' => 'Pukhrayan', 'state_id' => '26'),
 array( 'name' => 'Puranpur', 'state_id' => '26'),
 array( 'name' => 'Purquazi', 'state_id' => '26'),
 array( 'name' => 'Purwa', 'state_id' => '26'),
 array( 'name' => 'Rae Bareli', 'state_id' => '26'),
 array( 'name' => 'Rampur', 'state_id' => '26'),
 array( 'name' => 'Rampur Maniharan', 'state_id' => '26'),
 array( 'name' => 'Rasra', 'state_id' => '26'),
 array( 'name' => 'Rath', 'state_id' => '26'),
 array( 'name' => 'Renukoot', 'state_id' => '26'),
 array( 'name' => 'Reoti', 'state_id' => '26'),
 array( 'name' => 'Robertsganj', 'state_id' => '26'),
 array( 'name' => 'Rudauli', 'state_id' => '26'),
 array( 'name' => 'Rudrapur', 'state_id' => '26'),
 array( 'name' => 'Sadabad', 'state_id' => '26'),
 array( 'name' => 'Safipur', 'state_id' => '26'),
 array( 'name' => 'Saharanpur', 'state_id' => '26'),
 array( 'name' => 'Sahaspur', 'state_id' => '26'),
 array( 'name' => 'Sahaswan', 'state_id' => '26'),
 array( 'name' => 'Sahawar', 'state_id' => '26'),
 array( 'name' => 'Sahjanwa', 'state_id' => '26'),
 array( 'name' => 'Ghazipur', 'state_id' => '26'),
 array( 'name' => 'Sambhal', 'state_id' => '26'),
 array( 'name' => 'Samdhan', 'state_id' => '26'),
 array( 'name' => 'Samthar', 'state_id' => '26'),
 array( 'name' => 'Sandi', 'state_id' => '26'),
 array( 'name' => 'Sandila', 'state_id' => '26'),
 array( 'name' => 'Sardhana', 'state_id' => '26'),
 array( 'name' => 'Seohara', 'state_id' => '26'),
 array( 'name' => 'Hardoi', 'state_id' => '26'),
 array( 'name' => 'Rampur', 'state_id' => '26'),
 array( 'name' => 'Shahganj', 'state_id' => '26'),
 array( 'name' => 'Shahjahanpur', 'state_id' => '26'),
 array( 'name' => 'Shamli', 'state_id' => '26'),
 array( 'name' => 'Agra', 'state_id' => '26'),
 array( 'name' => 'Shamsabad', 'state_id' => '26'),
 array( 'name' => 'Sherkot', 'state_id' => '26'),
 array( 'name' => 'Shikarpur', 'state_id' => '26'),
 array( 'name' => 'Bulandshahr', 'state_id' => '26'),
 array( 'name' => 'Shikohabad', 'state_id' => '26'),
 array( 'name' => 'Shishgarh', 'state_id' => '26'),
 array( 'name' => 'Siana', 'state_id' => '26'),
 array( 'name' => 'Sikanderpur', 'state_id' => '26'),
 array( 'name' => 'Sikandra Rao', 'state_id' => '26'),
 array( 'name' => 'Sikandrabad', 'state_id' => '26'),
 array( 'name' => 'Sirsaganj', 'state_id' => '26'),
 array( 'name' => 'Sirsi', 'state_id' => '26'),
 array( 'name' => 'Sitapur', 'state_id' => '26'),
 array( 'name' => 'Soron', 'state_id' => '26'),
 array( 'name' => 'Suar', 'state_id' => '26'),
 array( 'name' => 'Sultanpur', 'state_id' => '26'),
 array( 'name' => 'Sumerpur', 'state_id' => '26'),
 array( 'name' => 'Tanda', 'state_id' => '26'),
 array( 'name' => 'Tanda', 'state_id' => '26'),
 array( 'name' => 'Tetri Bazar', 'state_id' => '26'),
 array( 'name' => 'Thakurdwara', 'state_id' => '26'),
 array( 'name' => 'Thana Bhawan', 'state_id' => '26'),
 array( 'name' => 'Tilhar', 'state_id' => '26'),
 array( 'name' => 'Tirwaganj', 'state_id' => '26'),
 array( 'name' => 'Tulsipur', 'state_id' => '26'),
 array( 'name' => 'Tundla', 'state_id' => '26'),
 array( 'name' => 'Unnao', 'state_id' => '26'),
 array( 'name' => 'Utraula', 'state_id' => '26'),
 array( 'name' => 'Varanasi', 'state_id' => '26'),
 array( 'name' => 'Vrindavan', 'state_id' => '26'),
 array( 'name' => 'Warhapur', 'state_id' => '26'),
 array( 'name' => 'Zaidpur', 'state_id' => '26'),
 array( 'name' => 'Zamania', 'state_id' => '26'),
 array( 'name' => 'Almora', 'state_id' => '27'),
 array( 'name' => 'Bazpur', 'state_id' => '27'),
 array( 'name' => 'Chamba', 'state_id' => '27'),
 array( 'name' => 'Dehradun', 'state_id' => '27'),
 array( 'name' => 'Haldwani', 'state_id' => '27'),
 array( 'name' => 'Haridwar', 'state_id' => '27'),
 array( 'name' => 'Jaspur', 'state_id' => '27'),
 array( 'name' => 'Kashipur', 'state_id' => '27'),
 array( 'name' => 'kichha', 'state_id' => '27'),
 array( 'name' => 'Kotdwara', 'state_id' => '27'),
 array( 'name' => 'Manglaur', 'state_id' => '27'),
 array( 'name' => 'Mussoorie', 'state_id' => '27'),
 array( 'name' => 'Nagla', 'state_id' => '27'),
 array( 'name' => 'Nainital', 'state_id' => '27'),
 array( 'name' => 'Pauri', 'state_id' => '27'),
 array( 'name' => 'Pithoragarh', 'state_id' => '27'),
 array( 'name' => 'Ramnagar', 'state_id' => '27'),
 array( 'name' => 'Rishikesh', 'state_id' => '27'),
 array( 'name' => 'Roorkee', 'state_id' => '27'),
 array( 'name' => 'Rudrapur', 'state_id' => '27'),
 array( 'name' => 'Sitarganj', 'state_id' => '27'),
 array( 'name' => 'Tehri', 'state_id' => '27'),
 array( 'name' => 'Muzaffarnagar', 'state_id' => '26'),
 array( 'name' => 'Adra', 'state_id' => '28'),
 array( 'name' => 'Alipurduar', 'state_id' => '28'),
 array( 'name' => 'Arambagh', 'state_id' => '28'),
 array( 'name' => 'Asansol', 'state_id' => '28'),
 array( 'name' => 'Baharampur', 'state_id' => '28'),
 array( 'name' => 'Bally', 'state_id' => '28'),
 array( 'name' => 'Balurghat', 'state_id' => '28'),
 array( 'name' => 'Bankura', 'state_id' => '28'),
 array( 'name' => 'Barakar', 'state_id' => '28'),
 array( 'name' => 'Barasat', 'state_id' => '28'),
 array( 'name' => 'Bardhaman', 'state_id' => '28'),
 array( 'name' => 'Bidhan Nagar', 'state_id' => '28'),
 array( 'name' => 'Chinsura', 'state_id' => '28'),
 array( 'name' => 'Contai', 'state_id' => '28'),
 array( 'name' => 'Cooch Behar', 'state_id' => '28'),
 array( 'name' => 'Darjeeling', 'state_id' => '28'),
 array( 'name' => 'Durgapur', 'state_id' => '28'),
 array( 'name' => 'Haldia', 'state_id' => '28'),
 array( 'name' => 'Howrah', 'state_id' => '28'),
 array( 'name' => 'Islampur', 'state_id' => '28'),
 array( 'name' => 'Jhargram', 'state_id' => '28'),
 array( 'name' => 'Kharagpur', 'state_id' => '28'),
 array( 'name' => 'Kolkata', 'state_id' => '28'),
 array( 'name' => 'Mainaguri', 'state_id' => '28'),
 array( 'name' => 'Mal', 'state_id' => '28'),
 array( 'name' => 'Mathabhanga', 'state_id' => '28'),
 array( 'name' => 'Medinipur', 'state_id' => '28'),
 array( 'name' => 'Memari', 'state_id' => '28'),
 array( 'name' => 'Monoharpur', 'state_id' => '28'),
 array( 'name' => 'Murshidabad', 'state_id' => '28'),
 array( 'name' => 'Nabadwip', 'state_id' => '28'),
 array( 'name' => 'Naihati', 'state_id' => '28'),
 array( 'name' => 'Panchla', 'state_id' => '28'),
 array( 'name' => 'Pandua', 'state_id' => '28'),
 array( 'name' => 'Paschim Punropara', 'state_id' => '28'),
 array( 'name' => 'Purulia', 'state_id' => '28'),
 array( 'name' => 'Raghunathpur', 'state_id' => '28'),
 array( 'name' => 'Raiganj', 'state_id' => '28'),
 array( 'name' => 'Rampurhat', 'state_id' => '28'),
 array( 'name' => 'Ranaghat', 'state_id' => '28'),
 array( 'name' => 'Sainthia', 'state_id' => '28'),
 array( 'name' => 'Santipur', 'state_id' => '28'),
 array( 'name' => 'Siliguri', 'state_id' => '28'),
 array( 'name' => 'Sonamukhi', 'state_id' => '28'),
 array( 'name' => 'Srirampore', 'state_id' => '28'),
 array( 'name' => 'Suri', 'state_id' => '28'),
 array( 'name' => 'Taki', 'state_id' => '28'),
 array( 'name' => 'Tamluk', 'state_id' => '28'),
 array( 'name' => 'Tarakeswar', 'state_id' => '28'),
 array( 'name' => 'Chikmagalur', 'state_id' => '11'),
 array( 'name' => 'Davanagere', 'state_id' => '11'),
 array( 'name' => 'Dharwad', 'state_id' => '11'),
 array( 'name' => 'Gadag', 'state_id' => '11'),
);
$timestamp = now();


foreach ($cities as &$city) {
    $city['created_at'] = $timestamp;
    $city['updated_at'] = $timestamp;
}

        DB::table('cities')->insert($cities);
    }
}
